# Generated by Django 4.0.6 on 2022-08-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='daily_timesheet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='daily_timesheets', to='manufacture.dailytimesheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='defect_individual',
            field=models.IntegerField(default=0, verbose_name='Брак с каждого рабочего'),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='rate_individual',
            field=models.IntegerField(default=0, verbose_name='Оплата каждому рабочему'),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='rate_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма оплаты за модель'),
        ),
        migrations.AddField(
            model_name='dailytimesheet',
            name='emp_count',
            field=models.IntegerField(default=0),
        ),
    ]
