# Generated by Django 4.0.6 on 2022-08-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_dailyproduction_daily_timesheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproduction',
            name='daily_timesheet',
        ),
        migrations.RemoveField(
            model_name='dailyproduction',
            name='defect_individual',
        ),
        migrations.RemoveField(
            model_name='dailyproduction',
            name='rate_individual',
        ),
        migrations.RemoveField(
            model_name='dailytimesheet',
            name='emp_count',
        ),
    ]
